import type { Endpoint, GraphQLOperation, ScanResult } from '../types.js';

export function generateOpenAPI(scan: ScanResult, options: { baseUrl: string }) {
  const paths: Record<string, any> = {};

  // 1. Procesar endpoints REST
  for (const endpoint of scan.endpoints) {
    if (endpoint.fileType === 'graphql') {
      continue;
    }

    const { openapiPath, params } = convertPathToOpenAPI(endpoint.path);

    if (!paths[openapiPath]) {
      paths[openapiPath] = {
        'x-routier-source-file': endpoint.sourceFile,
        'x-routier-router': endpoint.router,
        parameters: params.map((param) => ({
          name: param,
          in: 'path',
          required: true,
          schema: { type: 'string' },
        })),
      };
    }

    for (const method of endpoint.methods) {
      const lowerMethod = method.toLowerCase();
      paths[openapiPath][lowerMethod] = {
        summary: `${method} ${openapiPath}`,
        responses: {
          '200': {
            description: 'Successful response',
          },
        },
      };
    }
  }

  // 2. Procesar operaciones GraphQL
  for (const operation of scan.graphqlOperations) {
    const operationPath = `/api/graphql/${operation.type}/${operation.name}`;
    paths[operationPath] = {
      'x-routier-source-file': operation.sourceFile,
      post: {
        summary: `GraphQL ${operation.type === 'query' ? 'Query' : 'Mutation'}: ${operation.name}`,
        'x-routier-graphql': true,
        'x-routier-graphql-type': operation.type,
        'x-routier-graphql-name': operation.name,
        'x-routier-graphql-query': operation.body.query,
        'x-routier-graphql-variables': operation.body.variables,
        'x-routier-path': '/api/graphql',
        responses: {
          '200': {
            description: 'Successful GraphQL response',
          },
        },
      },
    };
  }

  // Asegurar que si hay endpoints de GraphQL se defina su ruta cruda
  const graphqlEndpoints = scan.endpoints.filter((e) => e.fileType === 'graphql');
  for (const ge of graphqlEndpoints) {
    if (!paths['/api/graphql']) {
      paths['/api/graphql'] = {
        'x-routier-source-file': ge.sourceFile,
        'x-routier-router': ge.router,
        post: {
          summary: 'GraphQL Endpoint',
          responses: {
            '200': {
              description: 'GraphQL Endpoint',
            },
          },
        },
      };
    }
  }

  return {
    openapi: '3.0.3',
    info: {
      title: 'Routier API',
      version: '1.0.0',
      description: 'Generated by Routier CLI',
    },
    servers: [
      {
        url: options.baseUrl,
      },
    ],
    paths,
  };
}

export function parseOpenAPI(openapi: any): ScanResult {
  const endpoints: Endpoint[] = [];
  const graphqlOperations: GraphQLOperation[] = [];

  const paths = openapi.paths ?? {};
  for (const [openapiPath, pathItem] of Object.entries(paths)) {
    const item = pathItem as any;
    
    // Convertir de vuelta {param} a :param
    const routePath = openapiPath.replace(/\{([^}]+)\}/g, ':$1');

    // Comprobar si esta ruta es una operación GraphQL extendida
    const hasGraphQLOperation = Object.values(item).some(
      (op: any) => op && typeof op === 'object' && op['x-routier-graphql']
    );

    if (hasGraphQLOperation) {
      for (const [method, op] of Object.entries(item)) {
        if (method === 'parameters' || method.startsWith('x-')) continue;
        const operation = op as any;
        if (operation['x-routier-graphql']) {
          graphqlOperations.push({
            type: operation['x-routier-graphql-type'],
            name: operation['x-routier-graphql-name'],
            arguments: [],
            variables: operation['x-routier-graphql-variables'] ?? {},
            body: {
              query: operation['x-routier-graphql-query'],
              variables: operation['x-routier-graphql-variables'] ?? {},
            },
            sourceFile: item['x-routier-source-file'] ?? '',
          });
        }
      }

      // Añadir el endpoint general de GraphQL si no está ya registrado
      const rawPath = '/api/graphql';
      if (!endpoints.some((e) => e.path === rawPath)) {
        endpoints.push({
          path: rawPath,
          methods: ['POST'],
          fileType: 'graphql',
          sourceFile: item['x-routier-source-file'] ?? '',
          router: item['x-routier-router'] ?? 'app',
        });
      }
    } else {
      // Reconstruir endpoint REST
      const sourceFile = item['x-routier-source-file'] ?? '';
      const router = item['x-routier-router'] ?? 'app';
      const methods = Object.keys(item)
        .filter((m) => !m.startsWith('x-') && m !== 'parameters')
        .map((m) => m.toUpperCase()) as any[];

      // Si la ruta cruda es el endpoint general de GraphQL (por ejemplo, si no hay operaciones registradas)
      const fileType = routePath === '/api/graphql' ? 'graphql' : 'rest';

      if (methods.length > 0 && !endpoints.some((e) => e.path === routePath)) {
        endpoints.push({
          path: routePath,
          methods,
          fileType,
          sourceFile,
          router,
        });
      }
    }
  }

  return {
    endpoints,
    graphqlOperations,
    warnings: [],
  };
}

function convertPathToOpenAPI(routePath: string) {
  const params: string[] = [];
  const matches = routePath.matchAll(/:([a-zA-Z0-9_]+)/g);
  for (const match of matches) {
    params.push(match[1]);
  }
  const openapiPath = routePath.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');
  return { openapiPath, params };
}
