import type { GroupBy, SortMode } from './index.js';
import type { Endpoint, GraphQLOperation, HttpMethod, ScanResult } from '../types.js';
import { parseOpenAPI } from '../generators/openapi.js';

interface ExportOptions {
  name?: string;
  baseUrl: string;
  groupBy?: GroupBy;
  sort?: SortMode;
}

interface RestRequest {
  endpoint: Endpoint;
  method: HttpMethod;
}

const METHOD_ORDER: HttpMethod[] = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];

export function generateInsomniaExport(openapi: any, options: ExportOptions) {
  const scan = parseOpenAPI(openapi);
  const workspaceId = 'wrk_routier';
  const environmentId = 'env_routier';
  const groupBy = options.groupBy ?? 'type';
  const sort = options.sort ?? 'alpha';
  
  const rawBaseUrl = openapi.servers?.[0]?.url ?? options.baseUrl;
  const isVariable = rawBaseUrl === '{baseUrl}' || rawBaseUrl === '{{baseUrl}}';
  const environmentBaseUrl = isVariable ? 'http://localhost:3000' : rawBaseUrl;

  const generatedIds = new Set<string>([workspaceId, environmentId]);

  const resources = [
    {
      _id: workspaceId,
      _type: 'workspace',
      name: options.name ?? 'Routier API',
      description: 'Generated by Routier',
      scope: 'collection',
    },
    {
      _id: environmentId,
      _type: 'environment',
      parentId: workspaceId,
      name: 'Base Environment',
      data: { baseUrl: environmentBaseUrl },
    },
    ...buildResources(scan, workspaceId, groupBy, sort, generatedIds),
  ];

  return {
    _type: 'export',
    __export_format: 4,
    __export_date: new Date(0).toISOString(),
    __export_source: 'routier-cli',
    resources,
  };
}

function buildResources(scan: ScanResult, workspaceId: string, groupBy: GroupBy, sort: SortMode, generatedIds: Set<string>) {
  const restRequests = scan.endpoints
    .filter((endpoint) => endpoint.fileType !== 'graphql')
    .flatMap((endpoint) => endpoint.methods.map((method) => ({ endpoint, method })));
  const graphqlEndpointRequests = scan.endpoints
    .filter((endpoint) => endpoint.fileType === 'graphql')
    .flatMap((endpoint) => endpoint.methods.map((method) => ({ endpoint, method })));
  const graphqlOperations = sortGraphqlOperations(scan.graphqlOperations, sort);

  if (groupBy === 'none') {
    return [
      ...sortRestRequests([...restRequests, ...graphqlEndpointRequests], sort)
        .map((request) => restToResource(request, workspaceId, generatedIds)),
      ...graphqlOperations.map((operation) => graphqlToResource(operation, workspaceId, generatedIds)),
    ];
  }

  if (groupBy === 'method') {
    return methodResources([...restRequests, ...graphqlEndpointRequests], workspaceId, sort, generatedIds);
  }

  if (groupBy === 'path') {
    return pathResources([...restRequests, ...graphqlEndpointRequests], graphqlOperations, workspaceId, sort, generatedIds);
  }

  const resources: unknown[] = [];
  const restFolderId = 'fld_rest';
  const graphqlFolderId = 'fld_graphql';

  if (restRequests.length > 0) {
    generatedIds.add(restFolderId);
    resources.push(folder(restFolderId, workspaceId, 'REST'));
    resources.push(...methodResources(restRequests, restFolderId, sort, generatedIds));
  }

  if (graphqlOperations.length > 0 || graphqlEndpointRequests.length > 0) {
    generatedIds.add(graphqlFolderId);
    resources.push(folder(graphqlFolderId, workspaceId, 'GraphQL'));

    const queryOperations = graphqlOperations.filter((operation) => operation.type === 'query');
    if (queryOperations.length > 0) {
      const queriesFolderId = 'fld_graphql_queries';
      generatedIds.add(queriesFolderId);
      resources.push(folder(queriesFolderId, graphqlFolderId, 'Queries'));
      resources.push(...queryOperations.map((operation) => graphqlToResource(operation, queriesFolderId, generatedIds)));
    }

    const mutationOperations = graphqlOperations.filter((operation) => operation.type === 'mutation');
    if (mutationOperations.length > 0) {
      const mutationsFolderId = 'fld_graphql_mutations';
      generatedIds.add(mutationsFolderId);
      resources.push(folder(mutationsFolderId, graphqlFolderId, 'Mutations'));
      resources.push(...mutationOperations.map((operation) => graphqlToResource(operation, mutationsFolderId, generatedIds)));
    }

    if (graphqlEndpointRequests.length > 0) {
      const endpointFolderId = 'fld_graphql_endpoint';
      generatedIds.add(endpointFolderId);
      resources.push(folder(endpointFolderId, graphqlFolderId, 'Endpoint'));
      resources.push(...sortRestRequests(graphqlEndpointRequests, sort).map((request) => restToResource(request, endpointFolderId, generatedIds)));
    }
  }

  return resources;
}

function methodResources(requests: RestRequest[], parentId: string, sort: SortMode, generatedIds: Set<string>) {
  const resources: unknown[] = [];

  for (const method of METHOD_ORDER) {
    const methodRequests = sortRestRequests(requests.filter((request) => request.method === method), sort);
    if (methodRequests.length === 0) continue;

    const folderId = resourceId(`fld_${parentId}_${method}`, generatedIds);
    resources.push(folder(folderId, parentId, method));
    resources.push(...methodRequests.map((request) => restToResource(request, folderId, generatedIds)));
  }

  return resources;
}

function pathResources(
  requests: RestRequest[],
  graphqlOperations: GraphQLOperation[],
  workspaceId: string,
  sort: SortMode,
  generatedIds: Set<string>,
) {
  const resources: unknown[] = [];
  const grouped = new Map<string, RestRequest[]>();

  for (const request of requests) {
    const segment = request.endpoint.path.split('/').filter(Boolean)[1] ?? 'root';
    grouped.set(segment, [...grouped.get(segment) ?? [], request]);
  }

  for (const [segment, segmentRequests] of [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const folderId = resourceId(`fld_path_${segment}`, generatedIds);
    resources.push(folder(folderId, workspaceId, segment));
    resources.push(...sortRestRequests(segmentRequests, sort).map((request) => restToResource(request, folderId, generatedIds)));
  }

  if (graphqlOperations.length > 0) {
    const folderId = 'fld_path_graphql_operations';
    generatedIds.add(folderId);
    resources.push(folder(folderId, workspaceId, 'graphql-operations'));
    resources.push(...sortGraphqlOperations(graphqlOperations, sort).map((operation) => graphqlToResource(operation, folderId, generatedIds)));
  }

  return resources;
}

function folder(id: string, parentId: string, name: string) {
  return {
    _id: id,
    _type: 'request_group',
    parentId,
    name,
  };
}

function restToResource(request: RestRequest, parentId: string, generatedIds: Set<string>) {
  const meta = request.endpoint.methodsMetadata?.[request.method];
  const headers = meta?.headers?.map((header) => {
    const isAuth = header.toLowerCase() === 'authorization';
    return {
      name: header,
      value: isAuth ? 'Bearer {{token}}' : `{{ _.${header.toLowerCase()} }}`,
    };
  }) ?? [];

  const body = meta?.body ? {
    mimeType: 'application/json',
    text: meta.body,
  } : {};

  return {
    _id: resourceId(`req_${parentId}_${request.method}_${request.endpoint.path}`, generatedIds),
    _type: 'request',
    parentId,
    name: `${request.method} ${request.endpoint.path}`,
    method: request.method,
    url: `{{ _.baseUrl }}${request.endpoint.path}`,
    headers,
    body,
  };
}

function graphqlToResource(operation: GraphQLOperation, parentId: string, generatedIds: Set<string>) {
  return {
    _id: resourceId(`req_${parentId}_graphql_${operation.type}_${operation.name}`, generatedIds),
    _type: 'request',
    parentId,
    name: operation.name,
    method: 'POST',
    url: '{{ _.baseUrl }}/api/graphql',
    headers: [{ name: 'Content-Type', value: 'application/json' }],
    body: {
      mimeType: 'application/json',
      text: JSON.stringify(operation.body, null, 2),
    },
  };
}

function sortRestRequests(requests: RestRequest[], sort: SortMode): RestRequest[] {
  if (sort === 'none') return requests;
  return [...requests].sort((a, b) => `${a.endpoint.path} ${a.method}`.localeCompare(`${b.endpoint.path} ${b.method}`));
}

function sortGraphqlOperations(operations: GraphQLOperation[], sort: SortMode): GraphQLOperation[] {
  if (sort === 'none') return operations;
  return [...operations].sort((a, b) => a.name.localeCompare(b.name));
}

function resourceId(value: string, generatedIds: Set<string>): string {
  const baseId = value.replace(/[^a-zA-Z0-9_]+/g, '_').replace(/^_+|_+$/g, '').toLowerCase();
  let uniqueId = baseId;
  let counter = 1;
  while (generatedIds.has(uniqueId)) {
    uniqueId = `${baseId}_${counter}`;
    counter++;
  }
  generatedIds.add(uniqueId);
  return uniqueId;
}
